### ISSUE TITLE
another mysterious set of caption buttons appear when maximized with aero

### ISSUE THREAD

**Issue by kokkermanz** [florinsdistortedvision/silverfox#12]
![image](https://github.com/florinsdistortedvision/silverfox/assets/89983730/616dfca8-0d01-4d74-848d-7ff100e47e9e)
![image](https://github.com/florinsdistortedvision/silverfox/assets/89983730/c10bf2ee-6cb6-4973-84c8-2f0d8552ab5e)
they respond to me hovering over the normal caption buttons

**Comment by florinsdistortedvision** [comment]
Like website says:
"Some themes such as Echelon, use the Native Controls Patch (xul.dll). If you are migrating from such themes, you MUST restore the original xul.dll Firefox comes with beforehand."

**Comment by kokkermanz** [comment]
![image](https://github.com/florinsdistortedvision/silverfox/assets/89983730/fd820676-6320-4fac-b60e-67dcdf869c68)
...still there...
