### ISSUE TITLE
Unable to download in Pale Moon

### ISSUE THREAD

**Issue by basilisk-dev** [florinsdistortedvision/silverfox#20]
You have [this JS](https://silverfox.neocities.org/components/JS/stopPaleIE.js) on your site which redirects Pale Moon browser users to [this page](https://silverfox.neocities.org/really).

If you don't "support old technologies" (Pale Moon receives updates regularly so it is not old), then wouldn't you want someone using an older browser to be able to download your browser?

**Comment by andyprough** [comment]
> You have [this JS](https://silverfox.neocities.org/components/JS/stopPaleIE.js) on your site which redirects Pale Moon browser users to [this page](https://silverfox.neocities.org/really).
> 
> If you don't "support old technologies" (Pale Moon receives updates regularly so it is not old), then wouldn't you want someone using an older browser to be able to download your browser?

It's called "punching up". One strategy to try to get attention for a project that no one knows about is to troll the established and popular projects above you. Probably won't work, but I'm sure the reason for trolling the various browsers is to try to get mentioned in the tech press as a meme project, start to get some attention and some downloads.

**Comment by florinsdistortedvision** [comment]
You guys are overthinking this, it's just a easter egg reference.

**Comment by basilisk-dev** [comment]
You are comparing Pale Moon to Internet Explorer, which is not valid.

**Comment by unix-supremacist** [comment]
an "easter egg" would not stop someone from downloading the project

**Comment by florinsdistortedvision** [comment]
> > You guys are overthinking this, it's just a easter egg reference.
> 
> 
> 
> This seems needlessly hostile for an "easter egg"...
> 
> I'd think it'd bite if Pale Moon's website flagged SilverFox and said "Silverfox, really? We don't allow people who use browser forks with less than 10 users. Please switch to a project people care about before accessing our site!". :/
> 
> 
> 
> Comparing Pale Moon to IE isn't cool, especially since Pale Moon is a mostly independent project that updates on it's own, and has even had occasions when it's fixed severe security issues before Firefox (in cases in which it was even affected to begin with).


That would be funny, but silverfox wouldn't be able to flagged since it's just a theme that doesn't spoof user agents or anything. Like I said, why would pale moon people care about a modern Firefox theme. It is the same reasoning as IE users. Use modern browsers if you want modern themes, and use Pale moon if you want Firefox 52 era themes.
