### ISSUE TITLE
Unable to download file if it's flagged as containing malware

### ISSUE THREAD

**Issue by veast-network** [florinsdistortedvision/silverfox#21]
Silverfox version: 1.1.1
OS: Windows 11 23H2 (22631)

*insert aggressive clicking noise here*

https://github.com/florinsdistortedvision/silverfox/assets/86145902/54d48adb-5ffc-456c-a0e9-9126be9a8e49

and the Downloads page only has an option to cancel
![image](https://github.com/florinsdistortedvision/silverfox/assets/86145902/1b13a535-9fb1-4c39-9441-e46e8f28214f)

**Comment by dominichayesferen** [comment]
Right-click the download on the bar.

That being said, this is ironically somewhat faithful as Chrome would just cancel the download automatically whenever a virus's detected.
