### ISSUE TITLE
Cant access extensions

### ISSUE THREAD

**Issue by lovebug0706** [florinsdistortedvision/silverfox#23]
Before this, I was able to access extensions on websites, but after the theme change, my pins were removed, and the extension menu wasnt there. I can still access the extension settings, but i cant pin anything. Maybe in the next update, can you fix this? Thank you.

**Comment by dominichayesferen** [comment]
Extensions can be accessed from the hamburger menu: Tools -> Extensions.

**Comment by lovebug0706** [comment]
Oh ok, thank you!
