### ISSUE TITLE
Still says native control patch is required when it is installed

### ISSUE THREAD

**Issue by LukasKlim** [florinsdistortedvision/silverfox#25]
![image](https://github.com/florinsdistortedvision/silverfox/assets/162822339/c52e2f23-195e-4800-b306-c0e6019c5d7a)
So for me when i install the native control patch, it just never works and i tried reinstalling firefox, refresh it, install it again but nothing works out. Is there a solution to fix it?

**Comment by dominichayesferen** [comment]
Fixed in 1.1.1.1
