### ISSUE TITLE
"Silverfox is unable to run its required JavaScript modules."

### ISSUE THREAD

**Issue by DaniJam05** [florinsdistortedvision/silverfox#30]
I have re-downloaded Silverfox three times now and installed the correct version of the Native Controls Patch and still it will not run the required JavaScript modules. 
I have repeated the installation process thrice, paying extra attention to steps 2 and 4, following them exactly how they were displayed on the installation page and still I am experiencing problems. 
I copied in the **chrome folder** and the **user.js** file into the proper profile folder, I **cleared the startup cache** using the button in **about:support**, and I installed the **Native Controls Patch** (at least the one that seems to work and stop giving me an error message, "**ESR 115.12.0**"), and I even **tried restoring defaults**. I'm still facing the same exact problem.
Is there anything I am unknowingly doing wrong? I am (assumedly) using the correct version, 115.6.0esr, which seems to switch over to being listed as 115.12.0esr when Silverfox is installed
![silverror](https://github.com/florinsdistortedvision/silverfox/assets/116296016/5d6cf5c9-54d3-4014-bfe6-15fdf826db14)

**Comment by averagescenekid** [comment]
same here on windows 7 ultimate x64, fully updated

**Comment by dominichayesferen** [comment]
Copy the Firefox Folder files to the Firefox folder.
