### ISSUE TITLE
no titlebar buttons

### ISSUE THREAD

**Issue by Victor35345-afk** [florinsdistortedvision/silverfox#31]
![image](https://github.com/florinsdistortedvision/silverfox/assets/151945968/b87105ef-717e-4b21-a745-d82867d02ef0)
if you don't know what os im using im using windows experience r2 from travis

**Comment by FlorianisonGitHub** [comment]
What browser is this?

**Comment by dominichayesferen** [comment]
This is fixed in Silverfox's upcoming successor, and is not planned to be rectified in Silverfox due to #24.
