### ISSUE TITLE
Request: Pre-2011 color theme

### ISSUE THREAD

**Issue by Nlk29** [florinsdistortedvision/silverfox#34]
Hello,

In the first versions of Google Chrome, the interface was a lot bluer and the new tab button had a plus-sign on it.
Since I really liked that design, i wanted to ask if there are any plans to add it to Silverfox?

![grafik](https://github.com/user-attachments/assets/3b7180e1-d2b1-4b96-bde4-fba76ef8084c)

**Comment by nexuz911** [comment]
SF Is not supported anymore i think,geckium is replacing it

**Comment by dominichayesferen** [comment]
This has been added in Geckium, Silverfox's upcoming successor. This was also planned for Silverfox 2.0, so regardless this would've happened. 
![image](https://github.com/user-attachments/assets/39b0ec22-8d5c-4df7-8cae-312392525dfd)
