### ISSUE TITLE
Entire window shifts up when maximised + bar at bottom of bookmarks + no hamburger menu + can't download anything

### ISSUE THREAD

**Issue by Marko2155** [florinsdistortedvision/silverfox#35]
When i double-click the top of the window the window goes from this:
<img width="1505" alt="Screenshot 2024-08-04 at 11 24 06 AM" src="https://github.com/user-attachments/assets/8f89af3a-a51a-40d6-9d19-c39b2c362f77">
to this:
<img width="1792" alt="Screenshot 2024-08-04 at 11 24 12 AM" src="https://github.com/user-attachments/assets/ecd2333b-7017-46ea-9f1c-2058769cfbb6">

I'm running MacOS Sonoma on a 13" M2 MacBook Pro for some information.
There's also this bar that stretches from one side of the screen to another and obstructs that part of the webpage.
Also there is no hamburger menu, just any extensions that i might be showing on the bar.
I also can't download anything, as nothing appears.

**Comment by dominichayesferen** [comment]
This won't be fixed as Silverfox is on life support until Geckium releases - see #24

**Comment by dominichayesferen** [comment]
That being said, you failed to install the required JS mods in the "Firefox Folder" folder.

**Comment by Marko2155** [comment]
Yeah i did!
I dragged the folders into the right places and restarted Firefox!
